language: python
sudo: required
services:
  - docker
#cache: pip
env:
  MIN_PYLINT_SCORE: 8
  WITH_INTEGRATION: 1
os:
  - linux
python:
  - "3.6"
script:
  - pip install pipenv
  - pipenv sync --dev
  - python nstest.py
  - pipenv install ./core
  - pipenv run pip show arxiv-base
  - pipenv run pytest --cov=agent/agent --cov=core/arxiv --cov-report=term-missing agent/agent core/arxiv
  # building sdist since travis-ci provider cannot do it in non-root directory
  - pip install setuptools ; cd agent ; python setup.py sdist ; cd .. ; cp -a agent/dist ./
after_success:
  - coveralls
#  - tests/lint.sh
  - tests/docstyle.sh
  - touch core/arxiv/__init__.py; ./tests/static.sh arxiv
  - pipenv run python -m arxiv.release.tag_check arxiv-submission-core
deploy:
- provider: pypi
  user: arxiv
  skip_cleanup: true
  password:
    secure: Hz66/lkqTH8/d0c5aF5+CWl2EhhRU6tBArQyeqjvC2rKR0Bx59yx8ZFbzfv0wjQkyOMjTD9DHqDkddqSWXMCSoCLheIfCkx27Irm5HGqxUxs4KulGoMTTD6l2091IfN3yv/EJ8QMN45DO4e3Fbtn/QMzDlaSRZrGIDkfMVZzu7Avgu2JncD4fPOdAq3kfSaSxFB2PC7vMsm4YDTKUvFNoDE7hlDUsEX/1HRHz2HMXJrmOT0bkCObuifnNfSs5Fg88Wvi3ca/vGwYwTUFWRqD2idGtE+Uh7mNGG55YPX5IqN8sLdCCOUYLM5LywRO8OmhGB2HO/nbgzDsvl2doWde5hVgtlE0sTGZb5HWVGgS0YOSfuPIOwPo/bTcQ/I8Bx3Sc99aC70mhJj4+NNBS7kcI34eCOnx1LwadICL7rsm2o6pT+T9ZY2zVVvSnrUzdIG30EDFo0GpG+k3sLtPIIgKhFg2fmDFg7vaOcH3KIadrUUQCuJzoD0W15sZ5zQ6YOdDzc6PpRAK3JMnmX43zINIxg6f3ohycJe2TuReZF88+6Zdx6EbWQD1audCBZapVV01iRW6D+XsyczeI/OK9xN+qPdGkfLqZC4/BQwPAnHWttDMDEj7iOceDZBUQcKa397wq8LHIpPG3h/zm91JXv5cgUSMj50fT/n0DDKwN3zsi1k=
  distributions: sdist
  on:
    tags: true
- provider: script
  script: python -m arxiv.release.docker_build_push ./ agent "$TRAVIS_TAG"
  on:
    tags: true
