language: python
sudo: required
services:
  - docker
#cache: pip
env:
  MIN_PYLINT_SCORE: 8
  WITH_INTEGRATION: 1
os:
  - linux
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv sync --dev
  # Build sdist since travis-ci provider cannot do it in non-root directory
  - pipenv run python -m arxiv.release.tag_check arxiv-submission-core
  - python setup.py sdist bdist_wheel
  - pipenv install dist/*.whl
  - git checkout -- Pipfile Pipfile.lock
script:
  - python nstest.py  
  - pipenv run pytest --cov=agent/agent --cov=core/arxiv --cov-report=term-missing agent/agent core/arxiv
after_success:
  - coveralls
#  - tests/lint.sh
  - tests/docstyle.sh
# python namespace package messes up mypy tests
  - touch core/arxiv/__init__.py; ./tests/static.sh arxiv; rm core/arxiv/__init__.py
deploy:
- provider: pypi
  skip_cleanup: true
  user: $PYPI_USERNAME
  password: $PYPI_TOKEN
  distributions: sdist
  on:
    tags: true
- provider: script
  skip_cleanup: true
  #docker build should pick up release tag from arxiv.release.tag_check
  script: python -m arxiv.release.docker_build_push ./ agent "$TRAVIS_TAG"
  on:
    tags: true
